const avartarIcons = [
    {img: './assets/avatar/avatar-icon-01.svg' },
    {img: './assets/avatar/avatar-icon-02.svg' },
    {img: './assets/avatar/avatar-icon-03.svg' },
    {img: './assets/avatar/avatar-icon-04.svg' },
    {img: './assets/avatar/avatar-icon-05.svg' },
    {img: './assets/avatar/avatar-icon-06.svg' },
    {img: './assets/avatar/avatar-icon-07.svg' },
    {img: './assets/avatar/avatar-icon-08.svg' },
    {img: './assets/avatar/avatar-icon-09.svg' },
    {img: './assets/avatar/avatar-icon-10.svg' },
    {img: './assets/avatar/avatar-icon-11.svg' },
    {img: './assets/avatar/avatar-icon-12.svg' },
    {img: './assets/avatar/avatar-icon-13.svg' },
    {img: './assets/avatar/avatar-icon-14.svg' },
    {img: './assets/avatar/avatar-icon-15.svg' },
    {img: './assets/avatar/avatar-icon-16.svg' },
    {img: './assets/avatar/avatar-icon-17.svg' },
    {img: './assets/avatar/avatar-icon-18.svg' },
    {img: './assets/avatar/avatar-icon-19.svg' },
    {img: './assets/avatar/avatar-icon-20.svg' },
    {img: './assets/avatar/avatar-icon-21.svg' },
    {img: './assets/avatar/avatar-icon-22.svg' },
    {img: './assets/avatar/avatar-icon-23.svg' },
    {img: './assets/avatar/avatar-icon-24.svg' },
    {img: './assets/avatar/avatar-icon-25.svg' },
    {img: './assets/avatar/avatar-icon-26.svg' },
    {img: './assets/avatar/avatar-icon-27.svg' },
    {img: './assets/avatar/avatar-icon-28.svg' },
    {img: './assets/avatar/avatar-icon-29.svg' },
    {img: './assets/avatar/avatar-icon-30.svg' },
    {img: './assets/avatar/avatar-icon-31.svg' },
    {img: './assets/avatar/avatar-icon-32.svg' },
    {img: './assets/avatar/avatar-icon-33.svg' },
    {img: './assets/avatar/avatar-icon-34.svg' },
    {img: './assets/avatar/avatar-icon-35.svg' },
    {img: './assets/avatar/avatar-icon-36.svg' },
    {img: './assets/avatar/avatar-icon-37.svg' },
    {img: './assets/avatar/avatar-icon-38.svg' },
    {img: './assets/avatar/avatar-icon-39.svg' },
    {img: './assets/avatar/avatar-icon-40.svg' },
    {img: './assets/avatar/avatar-icon-41.svg' },
    {img: './assets/avatar/avatar-icon-42.svg' },
    {img: './assets/avatar/avatar-icon-43.svg' },
    {img: './assets/avatar/avatar-icon-44.svg' },
    {img: './assets/avatar/avatar-icon-45.svg' },
    {img: './assets/avatar/avatar-icon-46.svg' },
    {img: './assets/avatar/avatar-icon-47.svg' },
    {img: './assets/avatar/avatar-icon-48.svg' },
  ];
  

  const pngAvatarIcons = [
    {img: './assets/avatar/png/jimis-avatar-icons-collection-01.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-02.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-03.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-04.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-05.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-06.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-07.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-08.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-09.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-10.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-11.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-12.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-13.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-14.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-15.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-16.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-17.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-18.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-19.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-20.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-21.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-22.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-23.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-24.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-25.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-26.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-27.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-28.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-29.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-30.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-31.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-32.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-33.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-34.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-35.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-36.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-37.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-38.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-39.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-40.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-41.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-42.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-43.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-44.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-45.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-46.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-47.png'},
    {img: './assets/avatar/png/jimis-avatar-icons-collection-48.png'},
  ]
  // export default avartarIcons
  export default pngAvatarIcons